language: node_js
node_js:
  - '8'
before_deploy:
  - npm run docs
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    keep-history: true
    committer-from-gh: true
    on:
      tags: true
